//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orm_ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string kullanici_adi { get; set; }
        public string parola { get; set; }
    }
}
