//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orm_ornek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int Id { get; set; }
        public string Urun_Ad { get; set; }
        public string Urun_Barkod { get; set; }
        public int Urun_Stok_Adet { get; set; }
        public System.DateTime Stok_Tarih { get; set; }
        public double Birim_Fiyat_Alis { get; set; }
        public double Birim_Fiyat_Satıs { get; set; }
        public int KDV { get; set; }
        public int Urun_Tedarikci { get; set; }
        public int MarkaId { get; set; }
    
        public virtual Markalar Markalar { get; set; }
    }
}
